micronaut:
  application:
    name: carrosGrpc
datasources:
  default:
    url: jdbc:mysql://localhost:3306/carros_grpc?createDatabaseIfNotExist=true&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: '1234'
    schema-generate: CREATE_DROP
    dialect: MYSQL
jpa:
  default:
    properties:
      hibernate.hbm2ddl.auto: update
      hibernate.show_sql: true
